### ISSUE TITLE
Cannot read property 'tarball' of undefined, version data absent

### ISSUE THREAD

**Issue by laurelnaiad** [jspm/npm#130]
Not sure why, but this error just began on my project out of seemingly thin air.

```bash
warn Error on download for npm:ansi-styles
     TypeError: Cannot read property 'tarball' of undefined
         at NPMLocation.download (/Users/dmaddox/Documents/_ws/myproj/node_modules/jspm-npm/lib/npm.js:338:45)
         at /Users/dmaddox/Documents/_ws/myproj/node_modules/jspm/lib/registry.js:117:30
         at lib$rsvp$$internal$$tryCatch (/Users/dmaddox/Documents/_ws/myproj/node_modules/rsvp/dist/rsvp.js:1036:16)
         at lib$rsvp$$internal$$invokeCallback (/Users/dmaddox/Documents/_ws/myproj/node_modules/rsvp/dist/rsvp.js:1048:17)
         at /Users/dmaddox/Documents/_ws/myproj/node_modules/rsvp/dist/rsvp.js:331:11
         at lib$rsvp$asap$$flush (/Users/dmaddox/Documents/_ws/myproj/node_modules/rsvp/dist/rsvp.js:1198:9)
         at _combinedTickCallback (node.js:376:9)
         at process._tickCallback (node.js:407:11)
```

ansi-styles is the first package that my build process actually finds it wants to download, so I guess I might also fail on package 2, 3 etc. as well.

The parameters coming in to the download function are:

* repo: 'ansi-styles'
* version: '^2.1.0'
* hash: ""
* versionData: { }

This was first reported to me around 1:15 pacific time on a build that seemed fine yesterday and I believe was fine earlier today as well.

???

**Comment by laurelnaiad** [comment]
By the way, the call out of registry.js on line 117 seems to be passing:

```
self: {"ui":{"logLevel":3,"format":{}},"name":"npm","tmpDir":"/Users/dmaddox/.jspm/npm-cache","remote":"https://npm.jspm.io","strictSSL":true,"alwaysAuth":false,"versionString":"jspm-npm@0.26"}
args: {"0":"ansi-styles","1":"^2.1.0","2":"","3":{},"4":"/Users/dmaddox/.jspm/packages/npm/ansi-styles@^2.1.0"}

```

which seems strange. It really should be looking to npm, not my cache. I already cleaned my cache, fwiw.

**Comment by laurelnaiad** [comment]
This was actually https://github.com/jspm/npm/issues/130
