### ISSUE TITLE
error npm install

### ISSUE THREAD

**Issue by filipemartinelli** [jspm/npm#155]
hello, I have an error when trying to run a simple npm install:

err  TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
         at fromObject (buffer.js:262:9)
         at Function.Buffer.from (buffer.js:101:10)
         at new Buffer (buffer.js:80:17)
         at decodeCredentials (/usr/lib/node_modules/jspm/node_modules/jspm-github/github.js:55:14)
         at Object.GithubLocation (/usr/lib/node_modules/jspm/node_modules/jspm-github/github.js:112:19)
         at Object.exports.load (/usr/lib/node_modules/jspm/lib/registry.js:73:56)
         at dl (/usr/lib/node_modules/jspm/lib/core.js:260:27)
         at /usr/lib/node_modules/jspm/lib/core.js:333:12
         at process._tickCallback (internal/process/next_tick.js:103:7)

jspm -v 0.16.46

**Comment by filipemartinelli** [comment]
i solve the problem.

jspm registry config github
